# Generated by Django 2.0.3 on 2018-05-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landinguser',
            old_name='code_postal',
            new_name='postal_code',
        ),
    ]
