# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landinguser',
            old_name='departement',
            new_name='code_postal',
        ),
    ]
