# Generated by Django 2.0.3 on 2018-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180524_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinguser',
            name='profile',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Pro', 'Professionnel de la santé')], default='Patient', max_length=64),
        ),
    ]
